import React from 'react';

const CountryOptions = () => (
	<>
		<option value='AF'>🇦🇫 Afghanistan (AF) +93</option>
		<option value='AL'>🇦🇱 Albania (AL) +355</option>
		<option value='DZ'>🇩🇿 Algeria (DZ) +213</option>
		<option value='AS'>🇦🇸 American Samoa (AS) +1-684</option>
		<option value='AD'>🇦🇩 Andorra (AD) +376</option>
		<option value='AO'>🇦🇴 Angola (AO) +244</option>
		<option value='AI'>🇦🇮 Anguilla (AI) +1-264</option>
		<option value='AQ'>🇦🇶 Antarctica (AQ) +672</option>
		<option value='AG'>🇦🇬 Antigua and Barbuda (AG) +1-268</option>
		<option value='AR'>🇦🇷 Argentina (AR) +54</option>
		<option value='AM'>🇦🇲 Armenia (AM) +374</option>
		<option value='AW'>🇦🇼 Aruba (AW) +297</option>
		<option value='AU'>🇦🇺 Australia (AU) +61</option>
		<option value='AT'>🇦🇹 Austria (AT) +43</option>
		<option value='AZ'>🇦🇿 Azerbaijan (AZ) +994</option>
		<option value='BS'>🇧🇸 Bahamas (BS) +1-242</option>
		<option value='BH'>🇧🇭 Bahrain (BH) +973</option>
		<option value='BD'>🇧🇩 Bangladesh (BD) +880</option>
		<option value='BB'>🇧🇧 Barbados (BB) +1-246</option>
		<option value='BY'>🇧🇾 Belarus (BY) +375</option>
		<option value='BE'>🇧🇪 Belgium (BE) +32</option>
		<option value='BZ'>🇧🇿 Belize (BZ) +501</option>
		<option value='BJ'>🇧🇯 Benin (BJ) +229</option>
		<option value='BM'>🇧🇲 Bermuda (BM) +1-441</option>
		<option value='BT'>🇧🇹 Bhutan (BT) +975</option>
		<option value='BO'>🇧🇴 Bolivia (BO) +591</option>
		<option value='BA'>🇧🇦 Bosnia and Herzegovina (BA) +387</option>
		<option value='BW'>🇧🇼 Botswana (BW) +267</option>
		<option value='BR'>🇧🇷 Brazil (BR) +55</option>
		<option value='IO'>🇮🇴 British Indian Ocean Territory (IO) +246</option>
		<option value='BN'>🇧🇳 Brunei (BN) +673</option>
		<option value='BG'>🇧🇬 Bulgaria (BG) +359</option>
		<option value='BF'>🇧🇫 Burkina Faso (BF) +226</option>
		<option value='BI'>🇧🇮 Burundi (BI) +257</option>
		<option value='KH'>🇰🇭 Cambodia (KH) +855</option>
		<option value='CM'>🇨🇲 Cameroon (CM) +237</option>
		<option value='CA'>🇨🇦 Canada (CA) +1</option>
		<option value='CV'>🇨🇻 Cape Verde (CV) +238</option>
		<option value='KY'>🇰🇾 Cayman Islands (KY) +1-345</option>
		<option value='CF'>🇨🇫 Central African Republic (CF) +236</option>
		<option value='TD'>🇹🇩 Chad (TD) +235</option>
		<option value='CL'>🇨🇱 Chile (CL) +56</option>
		<option value='CN'>🇨🇳 China (CN) +86</option>
		<option value='CX'>🇨🇽 Christmas Island (CX) +61</option>
		<option value='CC'>🇨🇨 Cocos (Keeling) Islands (CC) +61</option>
		<option value='CO'>🇨🇴 Colombia (CO) +57</option>
		<option value='KM'>🇰🇲 Comoros (KM) +269</option>
		<option value='CG'>🇨🇬 Republic of the Congo (CG) +242</option>
		<option value='CD'>🇨🇩 Democratic Republic of the Congo (CD) +243</option>
		<option value='CK'>🇨🇰 Cook Islands (CK) +682</option>
		<option value='CR'>🇨🇷 Costa Rica (CR) +506</option>
		<option value='HR'>🇭🇷 Croatia (HR) +385</option>
		<option value='CU'>🇨🇺 Cuba (CU) +53</option>
		<option value='CW'>🇨🇼 Curaçao (CW) +599</option>
		<option value='CY'>🇨🇾 Cyprus (CY) +357</option>
		<option value='CZ'>🇨🇿 Czech Republic (CZ) +420</option>
		<option value='DK'>🇩🇰 Denmark (DK) +45</option>
		<option value='DJ'>🇩🇯 Djibouti (DJ) +253</option>
		<option value='DM'>🇩🇲 Dominica (DM) +1-767</option>
		<option value='DO'>🇩🇴 Dominican Republic (DO) +1-809, 1-829, 1-849</option>
		<option value='EC'>🇪🇨 Ecuador (EC) +593</option>
		<option value='EG'>🇪🇬 Egypt (EG) +20</option>
		<option value='SV'>🇸🇻 El Salvador (SV) +503</option>
		<option value='GQ'>🇬🇶 Equatorial Guinea (GQ) +240</option>
		<option value='ER'>🇪🇷 Eritrea (ER) +291</option>
		<option value='EE'>🇪🇪 Estonia (EE) +372</option>
		<option value='ET'>🇪🇹 Ethiopia (ET) +251</option>
		<option value='FK'>🇫🇰 Falkland Islands (FK) +500</option>
		<option value='FO'>🇫🇴 Faroe Islands (FO) +298</option>
		<option value='FJ'>🇫🇯 Fiji (FJ) +679</option>
		<option value='FI'>🇫🇮 Finland (FI) +358</option>
		<option value='FR'>🇫🇷 France (FR) +33</option>
		<option value='GF'>🇬🇫 French Guiana (GF) +594</option>
		<option value='PF'>🇵🇫 French Polynesia (PF) +689</option>
		<option value='GA'>🇬🇦 Gabon (GA) +241</option>
		<option value='GM'>🇬🇲 Gambia (GM) +220</option>
		<option value='GE'>🇬🇪 Georgia (GE) +995</option>
		<option value='DE'>🇩🇪 Germany (DE) +49</option>
		<option value='GH'>🇬🇭 Ghana (GH) +233</option>
		<option value='GI'>🇬🇮 Gibraltar (GI) +350</option>
		<option value='GR'>🇬🇷 Greece (GR) +30</option>
		<option value='GL'>🇬🇱 Greenland (GL) +299</option>
		<option value='GD'>🇬🇩 Grenada (GD) +1-473</option>
		<option value='GP'>🇬🇵 Guadeloupe (GP) +590</option>
		<option value='GU'>🇬🇺 Guam (GU) +1-671</option>
		<option value='GT'>🇬🇹 Guatemala (GT) +502</option>
		<option value='GG'>🇬🇬 Guernsey (GG) +44-1481</option>
		<option value='GN'>🇬🇳 Guinea (GN) +224</option>
		<option value='GW'>🇬🇼 Guinea-Bissau (GW) +245</option>
		<option value='GY'>🇬🇾 Guyana (GY) +592</option>
		<option value='HT'>🇭🇹 Haiti (HT) +509</option>
		<option value='HN'>🇭🇳 Honduras (HN) +504</option>
		<option value='HK'>🇭🇰 Hong Kong (HK) +852</option>
		<option value='HU'>🇭🇺 Hungary (HU) +36</option>
		<option value='IS'>🇮🇸 Iceland (IS) +354</option>
		<option value='IN'>🇮🇳 India (IN) +91</option>
		<option value='ID'>🇮🇩 Indonesia (ID) +62</option>
		<option value='IR'>🇮🇷 Iran (IR) +98</option>
		<option value='IQ'>🇮🇶 Iraq (IQ) +964</option>
		<option value='IE'>🇮🇪 Ireland (IE) +353</option>
		<option value='IM'>🇮🇲 Isle of Man (IM) +44-1624</option>
		<option value='IL'>🇮🇱 Israel (IL) +972</option>
		<option value='IT'>🇮🇹 Italy (IT) +39</option>
		<option value='CI'>🇨🇮 Ivory Coast (CI) +225</option>
		<option value='JM'>🇯🇲 Jamaica (JM) +1-876</option>
		<option value='JP'>🇯🇵 Japan (JP) +81</option>
		<option value='JE'>🇯🇪 Jersey (JE) +44-1534</option>
		<option value='JO'>🇯🇴 Jordan (JO) +962</option>
		<option value='KZ'>🇰🇿 Kazakhstan (KZ) +7</option>
		<option value='KE'>🇰🇪 Kenya (KE) +254</option>
		<option value='KI'>🇰🇮 Kiribati (KI) +686</option>
		<option value='XK'>🇽🇰 Kosovo (XK) +383</option>
		<option value='KW'>🇰🇼 Kuwait (KW) +965</option>
		<option value='KG'>🇰🇬 Kyrgyzstan (KG) +996</option>
		<option value='LA'>🇱🇦 Laos (LA) +856</option>
		<option value='LV'>🇱🇻 Latvia (LV) +371</option>
		<option value='LB'>🇱🇧 Lebanon (LB) +961</option>
		<option value='LS'>🇱🇸 Lesotho (LS) +266</option>
		<option value='LR'>🇱🇷 Liberia (LR) +231</option>
		<option value='LY'>🇱🇾 Libya (LY) +218</option>
		<option value='LI'>🇱🇮 Liechtenstein (LI) +423</option>
		<option value='LT'>🇱🇹 Lithuania (LT) +370</option>
		<option value='LU'>🇱🇺 Luxembourg (LU) +352</option>
		<option value='MO'>🇲🇴 Macau (MO) +853</option>
		<option value='MK'>🇲🇰 North Macedonia (MK) +389</option>
		<option value='MG'>🇲🇬 Madagascar (MG) +261</option>
		<option value='MW'>🇲🇼 Malawi (MW) +265</option>
		<option value='MY'>🇲🇾 Malaysia (MY) +60</option>
		<option value='MV'>🇲🇻 Maldives (MV) +960</option>
		<option value='ML'>🇲🇱 Mali (ML) +223</option>
		<option value='MT'>🇲🇹 Malta (MT) +356</option>
		<option value='MH'>🇲🇭 Marshall Islands (MH) +692</option>
		<option value='MQ'>🇲🇶 Martinique (MQ) +596</option>
		<option value='MR'>🇲🇷 Mauritania (MR) +222</option>
		<option value='MU'>🇲🇺 Mauritius (MU) +230</option>
		<option value='YT'>🇾🇹 Mayotte (YT) +262</option>
		<option value='MX'>🇲🇽 Mexico (MX) +52</option>
		<option value='FM'>🇫🇲 Micronesia (FM) +691</option>
		<option value='MD'>🇲🇩 Moldova (MD) +373</option>
		<option value='MC'>🇲🇨 Monaco (MC) +377</option>
		<option value='MN'>🇲🇳 Mongolia (MN) +976</option>
		<option value='ME'>🇲🇪 Montenegro (ME) +382</option>
		<option value='MS'>🇲🇸 Montserrat (MS) +1-664</option>
		<option value='MA'>🇲🇦 Morocco (MA) +212</option>
		<option value='MZ'>🇲🇿 Mozambique (MZ) +258</option>
		<option value='MM'>🇲🇲 Myanmar (MM) +95</option>
		<option value='NA'>🇳🇦 Namibia (NA) +264</option>
		<option value='NR'>🇳🇷 Nauru (NR) +674</option>
		<option value='NP'>🇳🇵 Nepal (NP) +977</option>
		<option value='NL'>🇳🇱 Netherlands (NL) +31</option>
		<option value='NC'>🇳🇨 New Caledonia (NC) +687</option>
		<option value='NZ'>🇳🇿 New Zealand (NZ) +64</option>
		<option value='NI'>🇳🇮 Nicaragua (NI) +505</option>
		<option value='NE'>🇳🇪 Niger (NE) +227</option>
		<option value='NG'>🇳🇬 Nigeria (NG) +234</option>
		<option value='NU'>🇳🇺 Niue (NU) +683</option>
		<option value='NF'>🇳🇫 Norfolk Island (NF) +672</option>
		<option value='KP'>🇰🇵 North Korea (KP) +850</option>
		<option value='MP'>🇲🇵 Northern Mariana Islands (MP) +1-670</option>
		<option value='NO'>🇳🇴 Norway (NO) +47</option>
		<option value='OM'>🇴🇲 Oman (OM) +968</option>
		<option value='PK'>🇵🇰 Pakistan (PK) +92</option>
		<option value='PW'>🇵🇼 Palau (PW) +680</option>
		<option value='PS'>🇵🇸 Palestine (PS) +970</option>
		<option value='PA'>🇵🇦 Panama (PA) +507</option>
		<option value='PG'>🇵🇬 Papua New Guinea (PG) +675</option>
		<option value='PY'>🇵🇾 Paraguay (PY) +595</option>
		<option value='PE'>🇵🇪 Peru (PE) +51</option>
		<option value='PH'>🇵🇭 Philippines (PH) +63</option>
		<option value='PL'>🇵🇱 Poland (PL) +48</option>
		<option value='PT'>🇵🇹 Portugal (PT) +351</option>
		<option value='PR'>🇵🇷 Puerto Rico (PR) +1-787, 1-939</option>
		<option value='QA'>🇶🇦 Qatar (QA) +974</option>
		<option value='RE'>🇷🇪 Reunion (RE) +262</option>
		<option value='RO'>🇷🇴 Romania (RO) +40</option>
		<option value='RU'>🇷🇺 Russia (RU) +7</option>
		<option value='RW'>🇷🇼 Rwanda (RW) +250</option>
		<option value='BL'>🇧🇱 Saint Barthelemy (BL) +590</option>
		<option value='SH'>🇸🇭 Saint Helena (SH) +290</option>
		<option value='KN'>🇰🇳 Saint Kitts and Nevis (KN) +1-869</option>
		<option value='LC'>🇱🇨 Saint Lucia (LC) +1-758</option>
		<option value='MF'>🇲🇫 Saint Martin (MF) +590</option>
		<option value='PM'>🇵🇲 Saint Pierre and Miquelon (PM) +508</option>
		<option value='VC'>🇻🇨 Saint Vincent and the Grenadines (VC) +1-784</option>
		<option value='WS'>🇼🇸 Samoa (WS) +685</option>
		<option value='SM'>🇸🇲 San Marino (SM) +378</option>
		<option value='ST'>🇸🇹 Sao Tome and Principe (ST) +239</option>
		<option value='SA'>🇸🇦 Saudi Arabia (SA) +966</option>
		<option value='SN'>🇸🇳 Senegal (SN) +221</option>
		<option value='RS'>🇷🇸 Serbia (RS) +381</option>
		<option value='SC'>🇸🇨 Seychelles (SC) +248</option>
		<option value='SL'>🇸🇱 Sierra Leone (SL) +232</option>
		<option value='SG'>🇸🇬 Singapore (SG) +65</option>
		<option value='SX'>🇸🇽 Sint Maarten (SX) +1-721</option>
		<option value='SK'>🇸🇰 Slovakia (SK) +421</option>
		<option value='SI'>🇸🇮 Slovenia (SI) +386</option>
		<option value='SB'>🇸🇧 Solomon Islands (SB) +677</option>
		<option value='SO'>🇸🇴 Somalia (SO) +252</option>
		<option value='ZA'>🇿🇦 South Africa (ZA) +27</option>
		<option value='KR'>🇰🇷 South Korea (KR) +82</option>
		<option value='SS'>🇸🇸 South Sudan (SS) +211</option>
		<option value='ES'>🇪🇸 Spain (ES) +34</option>
		<option value='LK'>🇱🇰 Sri Lanka (LK) +94</option>
		<option value='SD'>🇸🇩 Sudan (SD) +249</option>
		<option value='SR'>🇸🇷 Suriname (SR) +597</option>
		<option value='SJ'>🇸🇯 Svalbard and Jan Mayen (SJ) +47</option>
		<option value='SZ'>🇸🇿 Eswatini (SZ) +268</option>
		<option value='SE'>🇸🇪 Sweden (SE) +46</option>
		<option value='CH'>🇨🇭 Switzerland (CH) +41</option>
		<option value='SY'>🇸🇾 Syria (SY) +963</option>
		<option value='TW'>🇹🇼 Taiwan (TW) +886</option>
		<option value='TJ'>🇹🇯 Tajikistan (TJ) +992</option>
		<option value='TZ'>🇹🇿 Tanzania (TZ) +255</option>
		<option value='TH'>🇹🇭 Thailand (TH) +66</option>
		<option value='TG'>🇹🇬 Togo (TG) +228</option>
		<option value='TK'>🇹🇰 Tokelau (TK) +690</option>
		<option value='TO'>🇹🇴 Tonga (TO) +676</option>
		<option value='TT'>🇹🇹 Trinidad and Tobago (TT) +1-868</option>
		<option value='TN'>🇹🇳 Tunisia (TN) +216</option>
		<option value='TR'>🇹🇷 Turkey (TR) +90</option>
		<option value='TM'>🇹🇲 Turkmenistan (TM) +993</option>
		<option value='TC'>🇹🇨 Turks and Caicos Islands (TC) +1-649</option>
		<option value='TV'>🇹🇻 Tuvalu (TV) +688</option>
		<option value='UG'>🇺🇬 Uganda (UG) +256</option>
		<option value='UA'>🇺🇦 Ukraine (UA) +380</option>
		<option value='AE'>🇦🇪 United Arab Emirates (AE) +971</option>
		<option value='GB'>🇬🇧 United Kingdom (GB) +44</option>
		<option value='US'>🇺🇸 United States (US) +1</option>
		<option value='UY'>🇺🇾 Uruguay (UY) +598</option>
		<option value='UZ'>🇺🇿 Uzbekistan (UZ) +998</option>
		<option value='VU'>🇻🇺 Vanuatu (VU) +678</option>
		<option value='VA'>🇻🇦 Vatican (VA) +379</option>
		<option value='VE'>🇻🇪 Venezuela (VE) +58</option>
		<option value='VN'>🇻🇳 Vietnam (VN) +84</option>
		<option value='VG'>🇻🇬 Virgin Islands, British (VG) +1-284</option>
		<option value='VI'>🇻🇮 Virgin Islands, U.S. (VI) +1-340</option>
		<option value='WF'>🇼🇫 Wallis and Futuna (WF) +681</option>
		<option value='EH'>🇪🇭 Western Sahara (EH) +212</option>
		<option value='YE'>🇾🇪 Yemen (YE) +967</option>
		<option value='ZM'>🇿🇲 Zambia (ZM) +260</option>
		<option value='ZW'>🇿🇼 Zimbabwe (ZW) +263</option>
	</>
);

export default CountryOptions;
