export const countryOptions = [
	{ value: 'AR', label: '🇦🇷 Argentina (AR) +54', code: '54' },
	{ value: 'AU', label: '🇦🇺 Australia (AU) +61', code: '61' },
	{ value: 'BE', label: '🇧🇪 Belgium (BE) +32', code: '32' },
	{ value: 'BR', label: '🇧🇷 Brazil (BR) +55', code: '55' },
	{ value: 'CA', label: '🇨🇦 Canada (CA) +1', code: '1' },
	{ value: 'CO', label: '🇨🇴 Colombia (CO) +57', code: '57' },
	{ value: 'CY', label: '🇨🇾 Cyprus (CY) +357', code: '357' },
	{ value: 'CZ', label: '🇨🇿 Czech Republic (CZ) +420', code: '420' },
	{ value: 'FR', label: '🇫🇷 France (FR) +33', code: '33' },
	{ value: 'DE', label: '🇩🇪 Germany (DE) +49', code: '49' },
	{ value: 'IE', label: '🇮🇪 Ireland (IE) +353', code: '353' },
	{ value: 'IL', label: '🇮🇱 Israel (IL) +972', code: '972' },
	{ value: 'IT', label: '🇮🇹 Italy (IT) +39', code: '39' },
	{ value: 'LU', label: '🇱🇺 Luxembourg (LU) +352', code: '352' },
	{ value: 'MT', label: '🇲🇹 Malta (MT) +356', code: '356' },
	{ value: 'MX', label: '🇲🇽 Mexico (MX) +52', code: '52' },
	{ value: 'NL', label: '🇳🇱 Netherlands (NL) +31', code: '31' },
	{ value: 'NZ', label: '🇳🇿 New Zealand (NZ) +64', code: '64' },
	{ value: 'NO', label: '🇳🇴 Norway (NO) +47', code: '47' },
	{ value: 'PH', label: '🇵🇭 Philippines (PH) +63', code: '63' },
	{ value: 'PT', label: '🇵🇹 Portugal (PT) +351', code: '351' },
	{ value: 'SG', label: '🇸🇬 Singapore (SG) +65', code: '65' },
	{ value: 'SK', label: '🇸🇰 Slovakia (SK) +421', code: '421' },
	{ value: 'ZA', label: '🇿🇦 South Africa (ZA) +27', code: '27' },
	{ value: 'ES', label: '🇪🇸 Spain (ES) +34', code: '34' },
	{ value: 'SE', label: '🇸🇪 Sweden (SE) +46', code: '46' },
	{ value: 'CH', label: '🇨🇭 Switzerland (CH) +41', code: '41' },
	{ value: 'GB', label: '🇬🇧 United Kingdom (GB) +44', code: '44' },
	{ value: 'US', label: '🇺🇸 United States (US) +1', code: '1' },
];
